import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import { MovieProvider } from "./providers/MovieProvider";

const karla = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <MovieProvider>
          {children}
        </MovieProvider>
      </body>
    </html>
  );
}
